name: Go

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Download Launcher Tarball
        run: |
          curl -L -o launcher-linux-arm64.tar.gz "https://github.com/discourse/launcher/releases/download/v2.0.1/launcher-linux-arm64.tar.gz"
          
      - name: Extract Launcher
        run: |
          tar -xzvf launcher-linux-arm64.tar.gz
      
      - name: Make Executable (if needed)
        run: |
          chmod +x launcher  # Adjust "launcher" to the extracted file name if different
      
      - name: Build Discourse
        run: |
          ./launcher build web_only