name: aelf discourse

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: aelf-discourse

    steps:
      - uses: actions/checkout@v4
      - name: Download Launcher Tarball
        run: |
          curl -L -o launcher-linux-amd64.tar.gz "https://github.com/discourse/launcher/releases/download/v2.0.1/launcher-linux-amd64.tar.gz"
          
      - name: Extract Launcher
        run: |
          tar -xzvf launcher-linux-amd64.tar.gz
      
      - name: Make Executable (if needed)
        run: |
          chmod +x launcher  # Adjust "launcher" to the extracted file name if different
      
      - name: Build Discourse
        run: |
          ./launcher build web_only

      - name: Set short git commit SHA
        id: vars
        run: |
          calculatedSha=$(git rev-parse --short ${{ github.sha }})
          echo "short_sha=$calculatedSha" >> "$GITHUB_OUTPUT"

      - name: Tag Docker Image
        run: docker tag docker.io/local_discourse/web_only:latest ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:sha-${{ steps.vars.outputs.short_sha }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:sha-${{ steps.vars.outputs.short_sha }}