name: Go

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.19', '1.20', '1.21.x' ]

    steps:
      - uses: actions/checkout@v4
      - name: Install launcher
        uses: jaxxstorm/action-install-gh-release@v1.10.0
        with:
          repo: discourse/launcher
      - run: launcher version